FROM --platform=linux/amd64 node:24-alpine

WORKDIR /app


RUN apk add --no-cache \
    g++ \
    python3 \
    openjdk17 

COPY package*.json ./

RUN npm install --production

COPY . .


CMD ["node", "worker.js"]
