services:
  redis:
    image: redis:7-alpine
    container_name: judge-redis
    ports:
      - "6379:6379"  
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

  judge:
    image: <905418426806>.dkr.ecr.<ap-south-1>.amazonaws.com/judge-service:latest
    container_name: judge-service
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  redis-data:
